package main

var gLangs = map[string]string{
	"zh-CN": "Chinese Simplified",
	"es":    "Spanish",
	// "ja":    "Japanese",
	// "de":    "German",
	// "fr":    "French",
	// "pt":    "Portuguese",
	// "ru":    "Russian",
	// "ar":    "Arabic",
	// "it":    "Italian",
	// "ko":    "Korean",
	// "zh-TW": "Chinese Traditional",
	// "nl":    "Dutch",
	// "tr":    "Turkish",
	// "pl":    "Polish",
	// "id":    "Indonesian",
	// "ms":    "Malay",
	// "th":    "Thai",
	// "sv":    "Swedish",
	// "no":    "Norwegian",
	// "el":    "Greek",
	// "cs":    "Czech",
	// "iw":    "Hebrew",
	// "da":    "Danish",
	// "ro":    "Romanian",
	// "vi":    "Vietnamese",
	// "fi":    "Finnish",
	// "uk":    "Ukrainian",
	// "hi":    "Hindi",
	// "hu":    "Hungarian",
	// "sk":    "Slovak",
}
